site_name: Agent Compose Kit
site_description: YAML-driven agent system builder for Google ADK (library-only)
site_url: https://deadmeme5441.github.io/agent-compose-kit/
repo_url: https://github.com/DeadMeme5441/agent-compose-kit
repo_name: DeadMeme5441/agent-compose-kit
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - llmstxt:
      markdown_description: |
        Agent Compose Kit turns YAML into ADK agent systems — services, tools, agents,
        registries, and a graph builder — all programmatic, built on google-adk and
        relying on google-adk-extras for durable backends.
      full_output: llms-full.txt
      sections:
        Overview:
        - index.md: What this package is and when to use it
        Installation:
        - install.md: Install with uv/pip and optional extras
        Configuration:
        - config.md: Configuration schema and validation
        Agents:
        - agents.md: LLM/workflow/custom agents and fields
        Tools:
        - tools.md: Function/MCP/OpenAPI/toolsets/built-ins
        Registries:
        - registries.md: Model aliases + declarative agent/tool registries
        Graph:
        - graph.md: Build a system graph (nodes/edges) with hints
        Quick Fixes:
        - quickfixes.md: Patch suggestions and how to apply
        Plan Lock:
        - plan_lock.md: Pin external refs and aliases (offline)
        Compose API:
        - api.md: Programmatic facade functions
        Examples:
        - examples.md: End-to-end usage snippets
docs_dir: docs
nav:
  - Overview: index.md
  - Installation: install.md
  - Configuration: config.md
  - Agents: agents.md
  - Tools: tools.md
  - Registries: registries.md
  - Graph: graph.md
  - Quick Fixes: quickfixes.md
  - Plan Lock: plan_lock.md
  - Compose API: api.md
  - Examples: examples.md
